[package]
name = "tcn75a"
version = "0.1.0"
authors = ["William D. Jones <thor0505@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0-alpha.1"

[dev-dependencies.embedded-hal-mock]
version = "0.8.0"
git = "https://github.com/eldruin/embedded-hal-mock"
branch = "embedded-hal-1.0.0-alpha"
